---
title: HJ Tech Contracting
bio: Linux Advocate , Tech Guy, Music Lover
description: HJ Tech Contracting - Linux Advocate , Tech Guy, Music Lover
reading_time: true
words_per_minute: 200
logo: assets/img/logo.svg
locale: en_US
url: http://0.0.0.0:4000
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
google:
  plus: JakeStrichek
email: hippyjake@gmail.com
github: hippyjake
steam: hippyjake
keybase: hippyjake
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
- jekyll-admin
- github-pages
- kickster
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- logs/
- Rakefile
- tester.sh
